<a href="https://colab.research.google.com/github/Sacheera127/Sentiment-Analysis-using-NLP/blob/colab/Sentiment_Analysis_using_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sentiment Analysis using NLP**

s**tep 1 - reading data & visualization** **bold text**

import libraries

In [ ]:

import pandas as pd
import nltk

##read datase

In [ ]:
df= pd.read_csv("/content/Tweets.csv",encoding="latin-1")

In [ ]:
df.head(5)

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [ ]:
df.shape

(14640, 15)

In [ ]:
df = df[["airline_sentiment", "text"]]

In [ ]:
df.head(5)

  airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [ ]:
df.rename(columns={"airline_sentiment": "sentiment", "text": "tweet"}, inplace=True)

In [ ]:
df.sample(5)

      sentiment                                              tweet
11940  negative  @AmericanAir I need a flight out tonight. Isn'...
2065   negative                       @united where is our luggage
7216   negative  @JetBlue Understood but I watched as fam headi...
11985  negative  @AmericanAir I'm not sure what happened to my ...
91      neutral  @VirginAmerica hi, i did not get points on my ...

In [ ]:
df.groupby("sentiment").describe()

          tweet
          count unique                                                top freq
sentiment
negative   9178   9087  @AmericanAir robocalls me with another Cancell...    2
neutral    3099   3067                                 @SouthwestAir sent    5
positive   2363   2298                                     @united thanks    5

In [ ]:
df= df.drop_duplicates(keep='first')

In [ ]:
df.groupby("sentiment").describe()

          tweet
          count unique                                                top freq
sentiment
negative   9087   9087  @AmericanAir you have my money, you change my ...    1
neutral    3067   3067  @AmericanAir we have 8 ppl so we need 2 know h...    1
positive   2298   2298  @AmericanAir thank you we got on a different f...    1

##data vizualization

In [ ]:
df["length"] = df["tweet"].apply(len)

In [ ]:
df.head(2)

  sentiment                                              tweet  length
0   neutral                @VirginAmerica What @dhepburn said.      35
1  positive  @VirginAmerica plus you've added commercials t...      72

##step 2- preprocessing

In [ ]:
import nltk

import string

import re



from nltk.stem.porter import PorterStemmer



nltk.download('stopwords')

from nltk.corpus import stopwords



nltk.download('punkt')

ps = PorterStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
df.head(5)

  sentiment                                              tweet  length
0   neutral                @VirginAmerica What @dhepburn said.      35
1  positive  @VirginAmerica plus you've added commercials t...      72
2   neutral  @VirginAmerica I didn't today... Must mean I n...      71
3  negative  @VirginAmerica it's really aggressive to blast...     126
4  negative  @VirginAmerica and it's a really big bad thing...      55

In [ ]:
def clean_text(text):
    # Convert to lowercase
    text = text.lower()

    # Tokenize the text
    text = nltk.word_tokenize(text)

    # Step 1: Keep only alphanumeric tokens
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)

    text = y[:]
    y.clear()

    # Step 2: Remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()


    for i in text:
         if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    # Step 3: Apply stemming
    for i in text:
        y.append(ps.stem(i))

    # Return as a single cleaned string
    return " ".join(y)

In [ ]:
import nltk
nltk.download('punkt_tab')
df['tweet cleaned'] = df['tweet'].apply(clean_text)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:

df.head(5)

,sentiment,tweet,length,tweet cleaned
0,neutral,@VirginAmerica What @dhepburn said.,35,virginamerica dhepburn said
1,positive,@VirginAmerica plus you've added commercials t...,72,virginamerica plu ad commerci experi tacki
2,neutral,@VirginAmerica I didn't today... Must mean I n...,71,virginamerica today must mean need take anoth ...
3,negative,@VirginAmerica it's really aggressive to blast...,126,virginamerica realli aggress blast obnoxi ente...
4,negative,@VirginAmerica and it's a really big bad thing...,55,virginamerica realli big bad thing

##feature extraction step-3

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf_vec= TfidfVectorizer(max_features=3000)
x=tf_vec.fit_transform(df['tweet cleaned']).toarray()

In [ ]:
x.shape

(14452, 3000)

In [ ]:
y=df['sentiment'].values

##step4-learning

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:

from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)

print(accuracy_score(y_test,y_pred))

0.7751643030093394